language: python
matrix:
  include:
    - python: 3.6
      env:
      - TOXENV=py36
    - python: 3.7
      env:
      - TOXENV=py37
    - python: 3.8
      env:
      - TOXENV=py38
    - python: pypy3
      env:
      - TOXENV=pypy3
install:
  - pip install tox coveralls
script:
  - tox
after_success:
  - coveralls
deploy:
  provider: pypi
  user: HoverHell
  distributions: sdist bdist_wheel
  on:
    condition: $TOXENV == py36
    tags: true
    all_branches: true
    repo: HoverHell/pylibosrm
